### ISSUE TITLE
How to link fragment add/remove with delegate/presenter ?

### ISSUE THREAD

**Issue by msimar** [joaquim-verges/Helium#11]

**Comment by joaquim-verges** [comment]
Adding and removing Fragments is something I would do inside the presenter, with the help of some sort of navigation class.

typical example would be on click or a menu, push the corresponding event from the view delegate, passing the context. Then in the presenter `onViewEvent()`, check for that event, then call `myNavigation.goTo(event.context as FragmentActivity, ...)`

and the `goTo()` method is what would the the actual fragment transaction.

**Comment by msimar** [comment]
Thank you for idea, It would be nice to have example under demo's

**Comment by joaquim-verges** [comment]
Good idea, i'll add a sample for this.
