### ISSUE TITLE
How Presenter/ViewDelegates will work with screen with map (markers)?

### ISSUE THREAD

**Issue by msimar** [joaquim-verges/Helium#13]

**Comment by joaquim-verges** [comment]
it should be possible to create map component using the helium pattern.

My first intuition is to make a presenter that implements the relevant callbacks for the Google Maps API (OnMapReadyCallback and co), and pass the presenter as the parameter of `SupportMapFragment .getMapAsync()`. From there you can write your logic as you normally would.
