### ISSUE TITLE
Fragment onActivityResult pushState failed to change ViewDelegate state

### ISSUE THREAD

**Issue by msimar** [joaquim-verges/Helium#15]
```
fragment.onActivityResult(...) {
  if (resultCode == Activity.RESULT_OK) {
    presenter.pushState(FragmentViewState.LoadResult(result))
 }
}
 
```

**Comment by joaquim-verges** [comment]
Thanks for pointing this out, this actually reveals an issue with Fragments starting activities in general.

The solution is to call `attach()` in `onStart` instead of `onCreateView`, this should solve your issue.

I'll update the sample code and docs to reflect this.

Thanks again!
