### ISSUE TITLE
[Question] Is it possible to unit test in this framework?

### ISSUE THREAD

**Issue by toddsantaniello** [joaquim-verges/Helium#21]
Hello Joaquim,

I'm evaluating your framework for adoption, I really like the approach and design (and your talk about it at droidcon). However, I'm finding it very difficult to actually write a unit test for our Presenters. Ideally, for testing we could attach our presenter to a mock delegate or stub implementation that we can use to verify view states as the presenter receives view events. This seems to be very difficult due to 1) the tight coupling between the Presenter and the LayoutInflater and 2) the reliance on the LifecycleObserver. I also notice there are no tests in any of the sample code. I'm curious if you have thoughts on testability, as that is a big priority for me and, imo, one of the main benefits of using MVP.

Cheers,
Todd

**Comment by joaquim-verges** [comment]
Hi Todd, thanks for your question!

I actually have some unit tests for [BasePresenter](https://github.com/joaquim-verges/Helium/blob/master/helium-core/src/test/java/com/joaquimverges/helium/core/presenter/BasePresenterTest.kt) and and [ListPresenter](https://github.com/joaquim-verges/Helium/blob/master/helium-ui/src/test/java/com/joaquimverges/helium/ui/presenter/ListPresenterTest.kt) which test pushing state / receiving events.

Although looking at them now, I'm not super happy with how I wrote them, I'll take some time to rewrite those, mainly I shouldn't have to rely on `spy` there.

It also gives me the idea that I could easily provide some `TestViewDelegate` class like I do in `BasePresenterTest` to make it convenient to test view event pushing.

But right now, you should be able to just use a mock view delegate right? Using a mock you could return your own event subject like: 

`whenever(myMockViewDelegate.observer()).thenReturn(myRealPublishSubject)`

then `myPresenter.attach(myMockViewDelegate)`

and then in your test, pushing events in your `myRealPublishSubject` should trigger a `onViewEvent()` in your presenter that you're testing.

let me know if that helps, and thanks again for the feedback! I definitely need to work a bit more on those unit tests.

**Comment by toddsantaniello** [comment]
Thanks for the quick reply @joaquim-verges ! I must've missed the tests in the BasePresenter and ListPresenter, thanks for pointing that out. I don't love the `spy` approach myself.

Regarding the mock approach, I receive this error when attempting to attach with a mock ViewDelegate:
```
java.lang.IllegalArgumentException: Cannot attach view delegates that don't have a lifecycle aware context
```
which I can see is an assertion at the start of the `attach` implementation. Unfortunately, the `val lifecycle` property in the `BaseViewDelegate` is type `internal` so I could not mock the `lifecycle`.

I also tried creating a `TestViewDelegate` class in my test, but run into the same issue with the lifecycle. I see you do not have that issue in your `BasePresenterTest` because it lives in the same package/namespace as the `BasePresenter` and thus you have: `whenever(viewDelegate.lifecycle).thenReturn(lifecycle)`.

Would you be up for making that lifecycle `protected` instead?

I'd love to use this framework if I could easily write Junit-only tests for my Presenter implementations where I assert expectations on ViewStates after receiving certain ViewEvents. I think what you have is great so far!

**Comment by joaquim-verges** [comment]
Hey @loopyzort !

I just pushed a change to my unit tests, and ended up introducing a new module: `helium-test` to help with unit testing!

you can add it to your dependencies as `testImplementation 'com.joaquimverges.helium:helium-test:0.3.0'` and get a nice `TestPresenter` and `TestViewDelegate` that I think are going to be very useful. Examples of usages are in [CoreTests ](https://github.com/joaquim-verges/Helium/blob/master/helium-test/src/test/java/com/joaquimverges/helium/test/CoreTests.kt) and [ListPresenterTests](https://github.com/joaquim-verges/Helium/blob/master/helium-ui/src/test/java/com/joaquimverges/helium/ui/presenter/ListPresenterTest.kt)

I also ended up changing `BaseViewDelegate` to have its `context` and `lifecycle` passed at construction time, so you can also easily mock them yourself now.

Let me know if that's better, and thanks again for the feedback!

**Comment by toddsantaniello** [comment]
Thanks again for the quick turnaround @joaquim-verges ! Sorry for the delays, I've recently left the project I was working on (for which we were evaluating a Helium integration). Your latest additions look great, though. Reading through the code, it should be much more testable. One thing that prevented us from integrating them, though, was our lack of androidx support. That's in the works, though, and I'm glad your library is upgraded to androidx, but that's the reason I couldn't provide any concrete feedback on your changes.

Anyhow, I think what you have in place is looking great and I'll definitely try it out for future projects.
