### ISSUE TITLE
[Question] Layers Questions

### ISSUE THREAD

**Issue by thim** [joaquim-verges/Helium#22]
Hi Joaquim,

Looking at the diagram the presenter layer is annotated with Kotlin code, however in the demo the presenter handle with activity and import some things from android, soon this layer was used with android. Is it correct? Is it possible to keep this layer purely kotlin?

Thanks to share the code.

**Comment by joaquim-verges** [comment]
I Thim, 

That's great feedback, I agree that right now the `Presenter` is a bit tied to Android right now. I could abstract it out a bit more to make it pure Kotlin, but want to understand what your goal is. Is it to be able to share the presenter layer for a multi-platform project?

**Comment by thim** [comment]
Hi,
first is to follow what your diagram specify, and second, yes, I trayed to think about multi-platform.

**Comment by joaquim-verges** [comment]
I'm looking into ways to make the framework multi platform friendly. I'll keep you posted :) thanks for the feedback!
