### ISSUE TITLE
getRetainedPresenter() only available in FragmentActivity

### ISSUE THREAD

**Issue by sal0max** [joaquim-verges/Helium#23]
Is there a reason that the `getRetainedPresenter()` extension method is only available for `FragmentActivity` and not for `AppCompatActivity` and regular `Activty`?

**Comment by joaquim-verges** [comment]
`AppCompatActivity` extends `FragmentActivity` so the extension function works fine with it. I use it all the time :)

I guess I could add one for regular Activity, but I feel like it's almost never used this days.
